"./sounds/portal/glad_os/stop_that-1.mp3":
   Overrides:
      1:
         Eye/IrisX: 8
      2.48612:
         Palette/SpeechOn:  0xBBB500
         Palette/SpeechOff: 0x407000
         Palette/SpeechDelay: 13
         Eye/Mood: angry
         Eye/Color: 0xBB2200
         Eye/IrisX: 1
      3.3:
         Palette/SpeechOn:  0xBB2200
      3.6:
         Palette/SpeechOn:   0xFF0000
"./sounds/portal/announcer/good.mp3":
   Overrides:
      0.001:
         Palette/SpeechOn: 0x00FF00
"./sounds/portal/i_guess/alert_status_red.mp3":
   Overrides:
      1.3:
         Palette/SpeechOn: 0xFF0000
         Palette/SpeechOff: 0xFF0000
"./sounds/portal/i_guess/error_organic_interference.mp3":
   Overrides:
      0.1: { "Palette/SpeechOn": 0xFF0000 }
      1.7: { "Palette/SpeechOn": 0xB09000 }
